spring:
  application:
    name: spring-session-demo
  main:
    banner-mode: off
  profiles:
    active: dev
  security:
    user:
      name: test-user
      password: password

logging:
  level:
    org.apache.tomcat: warn
    org.apache.catalina: warn
    org.apache.coyote: warn
    org.springframework: warn
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
